### ISSUE TITLE
flag 'Family member did not provide information'

### ISSUE THREAD

**Issue by pro100olga** [excieve/dragnet#36]
Searching through all sections, all objects and all its elements we need to find elements which have 'extendedstatus' in their names - and if at least one of the elements is equal to 3, flag is assigned True value.

Sample code in python is provided below

Name the variable family_member_did_not_provide_information.flag (True / False)

**Declarations to check:**

- should return False:

https://declarations.com.ua/declaration/nacp_c9e4d7dd-d6b7-44b8-9e26-12e756d36e04
https://declarations.com.ua/declaration/nacp_2ec7e56b-60b4-4d78-b3d7-50a2eae6b50b

- should return True:

https://declarations.com.ua/declaration/nacp_d31862b4-9e3b-43ef-926d-6d8b2cfe300a
https://declarations.com.ua/declaration/nacp_fd153b8b-849e-4fa2-9a09-fb54bfae3bdd

**Sample code:**

```
res = False # variable with result

for i in range(3,16): # go through all chapters (3-15, for 16 there is different approach below)
    step_i = 'step_' + str(i)
    if step_i in r['unified_source'].keys(): # check if chapter is in declaration
        for key_dict in r['unified_source'][step_i].keys(): # check all objects in each chapter
            # find all elements which have 'expendedstatus' in their names
            status_list = [s for s in list(r['unified_source'][step_i][key_dict].keys()) if "extendedstatus" in s]
            # check if any expended status element is equal to '3' (if yes  - we switch the flag to 1)
            for s in status_list:
                if r['unified_source'][step_i][key_dict][s] == '3':
                    res = True
                    break;
        if res:
            break;
            
if not res: # additional check of step 16 if result is still false
    if 'step_16' in r['unified_source'].keys():
        for step_16_el in r['unified_source']['step_16'].keys():
            for key_dict in r['unified_source']['step_16'][step_16_el]: # check all objects in each chapter
                # find all elements which have 'expendedstatus' in their names
                status_list = [s for s in list(r['unified_source']['step_16'][step_16_el][key_dict].keys()) if "extendedstatus" in s]
                # check if any expended status element is equal to '3' (if yes  - we switch the flag to 1)
                for s in status_list:
                    if r['unified_source']['step_16'][step_16_el][key_dict][s] == '3':
                        res = True
                        break;
```

**Final description of the flag (written before closing issue):**

- For all sections of the document (except first 2 - information about declarant and information about family):
  - For all objects in this section
    - Check the following list of fields, and if any of them is equal to 3 - raise a flag

The list of fields does not include some fields which are not very important or may be considered as unknown to a family member, e.g.: tax numbers, registration numbers, etc

The list is the following: 
'addition_firstname_extendedstatus', 'addition_lastname_extendedstatus', 'amount_extendedstatus', 'assetsCurrency_extendedstatus', 'brand_extendedstatus', 'costAssessment_extendedstatus', 'costDateOrigin_extendedstatus', 'costDateUse_extendedstatus', 'costDate_extendedstatus', 'cost_extendedstatus', 'cost_percent_extendedstatus', 'country_extendedstatus', 'dateUse_extendedstatus', 'descriptionObject_extendedstatus', 'emitent_eng_company_name_extendedstatus', 'emitent_eng_fullname_extendedstatus', 'emitent_extendedstatus', 'emitent_ua_company_name_extendedstatus', 'emitent_ua_fullname_extendedstatus', 'emitent_ukr_company_name_extendedstatus', 'emitent_ukr_fullname_extendedstatus', 'en_name_extendedstatus', 'graduationYear_extendedstatus', 'incomeSource_extendedstatus', 'manufacturerName_extendedstatus', 'model_extendedstatus', 'name_extendedstatus', 'objectType_extendedstatus', 'organization_eng_company_name_extendedstatus','organization_ua_company_name_extendedstatus'", 'organization_ukr_company_name_extendedstatus', 'otherObjectType_extendedstatus', 'owningDate_extendedstatus', 'propertyDescr_extendedstatus', 'sizeAssets_extendedstatus', 'sizeIncome_extendedstatus', 'source_eng_company_name_extendedstatus', 'source_ua_company_name_extendedstatus', 'source_ukr_company_name_extendedstatus', 'totalArea_extendedstatus', 'trademark_extendedstatus', "costDate_extendedstatus","owningDate_extendedstatus", "totalArea_extendedstatus", "source_ua_company_name_extendedstatus","percent-ownership_extendedstatus","costAssessment_extendedstatus"

**Comment by pro100olga** [comment]
Check result as of 24/02/20 (partial data 20+ K rows):

Checked 15 files, found 3 strange, but it seems this is a problem of the document, not the algorithm:
1) nacp_00db5a10-57e0-4930-86d6-df4715fe7ee2:
"regNumber_extendedstatus": "3" for estate object, while html shows "Реєстраційний номер: Конфіденційна інформація"
2) nacp_33456292-df74-404f-8ecc-dad67b2b7870
"taxNumber_extendedstatus": "3" for estate object, but there is something strange in json - looks like esatate data is substituted with data about companies
3) nacp_61e49df6-b224-4288-9b74-4c5be453e043
Also looks like json problem: status 3 defined for estate address (html shows  "Конфіденційна інформація"). While usually this type of hidden info has status "" in json

Still need to check on full dataset

**Comment by pro100olga** [comment]
Checked on partial data as of 01/03/20 (67K rows)

First, looks like there is more True values than before: 26K out of 67K (~39%), while in previous file there was 4.4K out of 22K (~20%)

Checked 5 files, all of them have some issues:

1) Flag assigned to True, but no such status neither in html, nor in json: 
nacp_00c09ff3-7149-4ebf-ae8a-a0ff0930d4c9
nacp_00c0a5db-8bc4-4688-8b8b-1a9e69010b01
nacp_00c0afb9-d0a7-41c8-b24f-590d0eaf37e9

2) nacp_00134760-696f-44be-98e9-c2576e2106af
"taxNumber_extendedstatus": "3" for step_2 section, which should not be checked

3) nacp_00c0ba4d-eeaa-4e89-a947-fdc69ed356b8
"ua_taxNumber_extendedstatus": "3" for estate object (rights section), looks like problem of json, not algorithm

**Comment by dchaplinsky** [comment]
Well, there are some misunderstanding.

You've been looking into different flag, which is
called family_member_did_not_provide_information_flag, that one is a legacy
one (but please check if BI is using it).

The one you need is family_member_did_not_provide_information (see, no
_flag at the end of the field name).

**Comment by pro100olga** [comment]
I see :) So, now family_member_did_not_provide_information field checked (as previously, on partial data, 67K rows)

5 files checked. 2 issues (see below). I think we need to redefine this flag. E.g., we do not need tax number of registration number statuses, as they are hidden anyway. I will elaborate on the requirements later

2 issues:

1) nacp_00c0ba4d-eeaa-4e89-a947-fdc69ed356b8
"ua_taxNumber_extendedstatus": "3" for estate object (rights section), looks like problem of json, not algorithm

2) nacp_001345dc-6cf3-4e39-b3fc-cbdaac1810d5
"regNumber_extendedstatus": "3" for estate object (html shows "Конфіденційна інформація"

**Comment by dchaplinsky** [comment]
Please elaborate

**Comment by pro100olga** [comment]
Instead of all names with 'extendedstatus' please use this list:

'addition_firstname_extendedstatus', 
'addition_lastname_extendedstatus',
'amount_extendedstatus', 
'assetsCurrency_extendedstatus', 
'brand_extendedstatus', 
'costAssessment_extendedstatus', 
'costDateOrigin_extendedstatus', 
'costDateUse_extendedstatus', 
'costDate_extendedstatus', 
'cost_extendedstatus', 
'cost_percent_extendedstatus', 
'country_extendedstatus', 
'dateUse_extendedstatus',
'descriptionObject_extendedstatus', 
'emitent_eng_company_name_extendedstatus', 
'emitent_eng_fullname_extendedstatus', 
'emitent_extendedstatus', 
'emitent_ua_company_name_extendedstatus', 
'emitent_ua_fullname_extendedstatus', 
'emitent_ukr_company_name_extendedstatus', 
'emitent_ukr_fullname_extendedstatus', 
'en_name_extendedstatus', 
'graduationYear_extendedstatus', 
'incomeSource_extendedstatus', 
'manufacturerName_extendedstatus', 
'model_extendedstatus', 
'name_extendedstatus',
'objectType_extendedstatus',
'organization_eng_company_name_extendedstatus', 'organization_ua_company_name_extendedstatus', 'organization_ukr_company_name_extendedstatus',
'otherObjectType_extendedstatus', 
'owningDate_extendedstatus', 
'propertyDescr_extendedstatus', 
'sizeAssets_extendedstatus',
'sizeIncome_extendedstatus',
'source_eng_company_name_extendedstatus',
'source_ua_company_name_extendedstatus',
'source_ukr_company_name_extendedstatus',
 'totalArea_extendedstatus',
 'trademark_extendedstatus'

**Comment by dchaplinsky** [comment]
That should be fixed, will send you updated sample shortly

**Comment by pro100olga** [comment]
Checked on partial data of annual decl-s for 2017 (~18K).

Is False, but should be True:
nacp_0001ecc7-15b6-4ad7-86be-43f219543c16
nacp_00c07b5a-b5e2-4cf5-a1fe-55a2751ffbea
nacp_00bed6fc-d2e8-4309-b309-f65ba7392987
nacp_00be9249-fe25-4d0d-b05d-d7e2b8daa455

**Comment by dchaplinsky** [comment]
Should be fixed now.

**Comment by pro100olga** [comment]
Checked on 500K documents from annual 2017 decl.
~1K mismatches, all False, but should be True.
E.g.:
nacp_d805ea50-ef97-4ad4-bc38-d34a2edd4d17
nacp_d80ad57d-c258-49b7-9edb-0089cb137622
nacp_d80b3698-a0fc-431a-af8e-771c6b7096a9
nacp_d80c80f3-4fe2-4f09-aeef-a47c9eedf66f

**Comment by dchaplinsky** [comment]
That's because your list of _extendedstatus was incomplete.

I'm adding following ones to the list:
"costDate_extendedstatus"
"owningDate_extendedstatus"
"totalArea_extendedstatus"
"source_ua_company_name_extendedstatus"
"percent-ownership_extendedstatus"
"costAssessment_extendedstatus"

Please also check list below if those are needed:
"taxNumber_extendedstatus"
"regNumber_extendedstatus"
"object_identificationNumber_extendedstatus"
"ua_apartmentsNum_extendedstatus"
"ua_housePartNum_extendedstatus"
"source_ua_company_name_extendedstatus"
"taxNumber_extendedstatus"

**Comment by pro100olga** [comment]
Checked 4 mismatches listed above, all ok
Will check on the full dataset later

These are not needed

> "taxNumber_extendedstatus"
> "regNumber_extendedstatus"
> "object_identificationNumber_extendedstatus"
> "ua_apartmentsNum_extendedstatus"
> "ua_housePartNum_extendedstatus"
> "source_ua_company_name_extendedstatus"
> "taxNumber_extendedstatus"

**Comment by pro100olga** [comment]
Checked on 500K documents (annual declarations from 2017) using [this code](https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020)

**All ok. Closed.** 

**Final description of the flag:**

- For all sections of the document (except first 2 - information about declarant and information about family):
  - For all objects in this section
    - Check the following list of fields, and if any of them is equal to 3 - raise a flag

The list of fields does not include some fields which are not very important or may be considered as unknown to a family member, e.g.: tax numbers, registration numbers, etc

The list is the following: 
'addition_firstname_extendedstatus', 'addition_lastname_extendedstatus', 'amount_extendedstatus', 'assetsCurrency_extendedstatus', 'brand_extendedstatus', 'costAssessment_extendedstatus', 'costDateOrigin_extendedstatus', 'costDateUse_extendedstatus', 'costDate_extendedstatus', 'cost_extendedstatus', 'cost_percent_extendedstatus', 'country_extendedstatus', 'dateUse_extendedstatus', 'descriptionObject_extendedstatus', 'emitent_eng_company_name_extendedstatus', 'emitent_eng_fullname_extendedstatus', 'emitent_extendedstatus', 'emitent_ua_company_name_extendedstatus', 'emitent_ua_fullname_extendedstatus', 'emitent_ukr_company_name_extendedstatus', 'emitent_ukr_fullname_extendedstatus', 'en_name_extendedstatus', 'graduationYear_extendedstatus', 'incomeSource_extendedstatus', 'manufacturerName_extendedstatus', 'model_extendedstatus', 'name_extendedstatus', 'objectType_extendedstatus', 'organization_eng_company_name_extendedstatus','organization_ua_company_name_extendedstatus'", 'organization_ukr_company_name_extendedstatus', 'otherObjectType_extendedstatus', 'owningDate_extendedstatus', 'propertyDescr_extendedstatus', 'sizeAssets_extendedstatus', 'sizeIncome_extendedstatus', 'source_eng_company_name_extendedstatus', 'source_ua_company_name_extendedstatus', 'source_ukr_company_name_extendedstatus', 'totalArea_extendedstatus', 'trademark_extendedstatus', "costDate_extendedstatus","owningDate_extendedstatus", "totalArea_extendedstatus", "source_ua_company_name_extendedstatus","percent-ownership_extendedstatus","costAssessment_extendedstatus"
