### ISSUE TITLE
add flag "has huge prize"

### ISSUE THREAD

**Issue by pro100olga** [excieve/dragnet#37]
Задекларовано виграші в лотерею чи призи вартістю більше 10 тис. грн
Income from lotteries / prizes > 10K UAH
Includes parsing of "other" field for prizes, lotteries, wons (призи, виграші, лотереї)

**Final description of the flag (written before closing the issue):** 

- Check all income objects, where 
 - - type of income is "Приз"
- - type of income is "Інше" and description satisfies /\Bвигра/i, /\Bлотере/i, /мегалот/i, /суперлото/i, /\Bпризові\B/i, /\Bпризи\B/i, /\Bпризів\B/i]
- Calculate sum of such income objects (transfer sum to UAH if needed)
- If total sum is >= 10'000 UAH - raise the flag

**Comment by pro100olga** [comment]
Checked on partial dataset as of 24/02/20 - all ok

Still need to check on full dataset

**Comment by pro100olga** [comment]
Checked on annual 2017 declarations (~800K) using this code:
https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020

Documents where flag is False, but should be True:
nacp_4776b36b-e694-4700-ba5b-8310bc16f6c6
nacp_473021e8-912f-47a2-9dc7-97720e720b34

- I guess the reason here is how search in "other" field is performed. I looked for "приз|вигр|выигр|лотер" during check. However this is not optimal either, as marks True such text as "виплата до призову до мобілізації" or "сума призначеної субсидії"

@dchaplinsky Please provide description of the search criteria so that it is documented in testing.

**Comment by dchaplinsky** [comment]
"вигра", "лотере", "мегалот", "суперлото", "призові"

**Comment by dchaplinsky** [comment]
I've switched it to /\Bвигра/i, /\Bлотере/i, /мегалот/i, /суперлото/i,
/\Bпризові\B/i, /\Bпризи\B/i, /\Bпризів\B/i]

**Comment by pro100olga** [comment]
Checked on partial data of annual decl-s for 2017 (~18K).

All ok. Will check on larger dataset.

**Comment by pro100olga** [comment]
Checked on 500K documents from annual 2017 decl.
3 mismatches

Is False, but should be True:
nacp_dc7848f1-4179-4b78-8258-45fc5bb6235f
nacp_fae03f5f-fbf7-4af7-9589-b685a5e0a78b
nacp_fc87e54a-4499-4452-9e26-bcaefbac8643

**Comment by dchaplinsky** [comment]
Hmm, again, all of them are True in my case.

Will send updated file shortly.

**Comment by pro100olga** [comment]
Checked 3 mismatches mentioned above - all ok.
Will check on full dataset later

**Comment by pro100olga** [comment]
Checked on 500K documents (annual declarations from 2017) using [this code](https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020)

**All ok. Closed.** 

**Final description of the flag:**

- Check all income objects, where 
 - - type of income is "Приз"
- - type of income is "Інше" and description satisfies /\Bвигра/i, /\Bлотере/i, /мегалот/i, /суперлото/i, /\Bпризові\B/i, /\Bпризи\B/i, /\Bпризів\B/i]
- Calculate sum of such income objects (transfer sum to UAH if needed)
- If total sum is >= 10'000 UAH - raise the flag
