### ISSUE TITLE
add flag "has_non_bank_liabilities"

### ISSUE THREAD

**Issue by pro100olga** [excieve/dragnet#38]
Description:
According to https://github.com/excieve/dragnet/issues/31 
using edrpou codes and these words in company name:
"твбв", "ощадбанк", "приватбанк", "аваль", "райффайзен", "абанк", "агріколь", "укрсиббанк", "альфабанк", "пумб", "укргазбанк", "мегабанк", "акордбанк", "сбербанк", "таскомбанк", "кредобанк", "індустріалбанк", "укрексімбанк", "радабанк", "укркомунбанк", "укрбудінвестбанк", "правексбанк", "правекс", "прокредит", "метабанк", "комінвестбанк", "форвард",

**Comment by pro100olga** [comment]
Checked on partial data (67K rows)
10 files checked

1) nacp_00c0c49c-f7dd-42b2-b971-e5dca23a4f6b
Has EDRPOU 34047020 (Дельта-банк), but flag is set to True

**Comment by dchaplinsky** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/131186/76471120-81455580-63fa-11ea-89d5-f9a14270bd09.png">
Well.

**Comment by pro100olga** [comment]
Ok, need to check on full dataset

**Comment by pro100olga** [comment]
Checked on annual 2017 declarations (~800K) using this code:
https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020

@dchaplinsky 
Please add to the list of bank names: "укрсоцбанк"

Also, do you use the list of banks' edrpou codes? 
See this documents for example: 
nacp_00c80022-4f89-4c38-9461-b7dcac085b21
nacp_04f51beb-a7f9-42c2-8d94-998142567ab7
nacp_2eb2c806-cd3d-423d-aa65-9dbbcf6ee296
Flag is set to True, while should be False

Also, see here - flag is set to False, while should be True:
nacp_4b2fcafe-c18f-45e4-aa92-b13997b1534a

**Comment by dchaplinsky** [comment]
re: nacp_4b2fcafe-c18f-45e4-aa92-b13997b1534a
Why should it be? last 3 records are about insurance.

Also, could you provide me some true positives for this one please?

**Comment by pro100olga** [comment]
Checked on partial data of annual decl-s for 2017 (~18K).

False, but should be True:
- nacp_00c0c49c-f7dd-42b2-b971-e5dca23a4f6b
First item has wrong EDRPOU code, also bank name is not in the list (Delta), so it should be considered as non-bank liabilities (though actually it is bank)

True, but should be False:
- nacp_00c1b5a0-49b2-43ae-82f3-31489d5d091b
Do you check otherObjectType? I checked for "страх|пенс|л[і|и]з[і|и]нг"

**Comment by dchaplinsky** [comment]
Should be fixed now.

**Comment by pro100olga** [comment]
Checked on ~500K documents from annual 2017 decl
~300 mismatches, all False, but should be True

nacp_eb116aaa-d89d-4ec4-b236-c7b24e5f8101
nacp_efeadb4e-69c9-47ea-8b2e-bd0604a16eee - here bank name is "альфа банк", but the list of banks names has "альфабанк", so the result should be True (non bank object). 
nacp_efd289a8-74b9-4b9a-8cba-6f7d7f49504e

**Comment by dchaplinsky** [comment]
Again, I've checked it on a fresh copy and all of them are good.
I've added Альфа банк to the list tho

**Comment by pro100olga** [comment]
Checked 3 mismatches mentioned above - all ok.
Will check on full dataset later

**Comment by pro100olga** [comment]
Checked on 500K documents (annual declarations from 2017) using [this code](https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020)

**All ok. Closed.** 

**Final description of the flag:**
Check all financial obligations. Raise the flag if there is an object for which:
- emitent registration code is in list of banks' EDRPOU codes ([code for obtaining this list](https://github.com/pro100olga/declarations/blob/master/bi/red_flags/liabilities_not_banks_insurance_leasing.py)) OR
- emitent name is in the following list
"твбв",        "ощадбанк",        "приватбанк",        "аваль",        "райффайзен",        "абанк",        "агріколь",        "укрсиббанк",        "альфабанк",        "альфа банк",        "альфа-банк",        "пумб",        "укргазбанк",        "мегабанк",        "акордбанк",        "сбербанк",        "таскомбанк",        "кредобанк",        "індустріалбанк",        "укрексімбанк",        "радабанк",        "укркомунбанк",        "укрбудінвестбанк",        "правексбанк",        "правекс",        "прокредит",        "метабанк",        "комінвестбанк",        "форвард",        "дельта-банк",        "дельтабанк",        "укрсоцбанк",        "дельта банк"
OR 
- object type or description of "Other" type contains insurance, leasing or pension funds
