### ISSUE TITLE
add flag "has_aircraft_flag"

### ISSUE THREAD

**Issue by pro100olga** [excieve/dragnet#39]
Has aircraft (повітряний транспортний засіб)

**Final description of the flag:**
Check all transport objects, if any of them has object type "Повітряний засіб" - raise a flag (regardless of owning or anything else)

**Comment by pro100olga** [comment]
Checked on partial data as of 24/02/20 (~22K rows) - one True value, ok.
Checked on partial data as of 01/03/20 (~67Krows) - no True values, no check.

Need to check on full dataset

**Comment by pro100olga** [comment]
Checked on annual 2017 declarations (~800K) using this code:
https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020

One mismatch: nacp_2cf2f35c-7468-4f9f-8713-3a6d202cf9eb
Should be True, but value is False

@dchaplinsky please check

**Comment by dchaplinsky** [comment]
In this case there are ownership rights are "permission to use". Should we
broaden it?

**Comment by pro100olga** [comment]
Nope, let' leave as it is.

Checked on partial data of annual decl-s for 2017 (~18K).

All ok. Will check on larger dataset.

**Comment by dchaplinsky** [comment]
У розділі декларації "Цінне рухоме майно - транспортні засоби" зазначено наявність транспортного засобу виду "Повітряний засіб" (поле "Вид майна")
--


I'll amend the rule to remove requirement on ownership

**Comment by pro100olga** [comment]
Ok, will check then on the full dataset

**Comment by dchaplinsky** [comment]
Should be fixed now.

**Comment by pro100olga** [comment]
Checked on 500K documents from annual 2017
2 mismatches

Is False, but should be True:
nacp_dd2e6933-e610-47e8-8625-3a756ef695e7
nacp_ec41e3a3-929a-4212-b04a-160c8f02dae8

**Comment by dchaplinsky** [comment]
On my copy it's perfectly fine. Will update you shortly

**Comment by pro100olga** [comment]
Checked 2 mismatches mentioned above, all ok
Will check on full dataset later

**Comment by pro100olga** [comment]
Checked on 500K documents (annual declarations from 2017) using [this code](https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020)

**All ok. Closed.** 

**Final description of the flag:**
Check all transport objects, if any of them has object type "Повітряний засіб" - raise a flag (regardless of owning or anything else)
