### ISSUE TITLE
add flag "has_foreign_real_estate"

### ISSUE THREAD

**Issue by pro100olga** [excieve/dragnet#41]
Has real estate object (житлова нерухомість) abroad (on any form of owning)

**Comment by pro100olga** [comment]
Checked on partial data (67K rows)
10 files checked - all ok

Need to check on full dataset

**Comment by pro100olga** [comment]
Checked on annual 2017 declarations (~800K) using this code:
https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020

Detected 193 documents where flag is False while should e True, e.g.:
nacp_4a0bd17e-56ed-40f1-a16f-4a158da17319
nacp_49d7133e-4733-4dbe-8f3e-993294ed4b45
nacp_497640d3-9a40-484a-8a3c-3a00e9d57cc4
nacp_44b164c6-edb0-4fe0-b7b8-e062c79144ea
nacp_4538c079-501d-46b6-9d84-40d39c3288a0

Is ownership somehow considered here? Cause these declarations above all have estate objects abroad on leasing \ free of charge usage, etc

@dchaplinsky please comment

**Comment by dchaplinsky** [comment]
У розділі декларації "Об’єкти нерухомості" зазначено об’єкт нерухомості, що належить суб’єкту декларування або члену сім’ї на праві власності, спільної власності, або власником об’єкта є третя особа, якщо при цьому країною місцезнаходження такого об’єкта є інша країна, ніж Україна

**Comment by pro100olga** [comment]
Checked on partial data of annual decl-s for 2017 (~18K).

False, but should be True:
nacp_e53295ab-148f-4ce8-a4d9-24299cfc04d2

**Comment by dchaplinsky** [comment]
Should be fixed now (she had other real estate type)

**Comment by pro100olga** [comment]
Checked on ~500K documents from annual 2017 decl
~100 mismatches

nacp_d88d3f32-43de-4ac8-be9e-7f8051e68cbf
nacp_ea669f79-1383-4ba7-a7c7-ac60ea8cdd21

Is it filtered for type of estate? 
E.g., here
nacp_d734faa3-39d2-4b46-b29b-18d481feeab0
there is garage and office abroad

True, but should be False
nacp_4a0bd17e-56ed-40f1-a16f-4a158da17319
nacp_e57e2217-c5cf-433b-b019-2f7a212b8b76
nacp_a12c37f8-4719-45be-9109-905ff8cc923d

**Comment by dchaplinsky** [comment]
wrt "True, but should be False"

Previously you wrote:
>Is ownership somehow considered here? Cause these declarations above all
have estate objects abroad on leasing \ free of charge usage, etc
So I've removed a clause on ownership rights and now considering any kind
of ownership rights. Should I move it back? Should I limit them to some
list? Please, advice

**Comment by pro100olga** [comment]
My suggestions:
- no limit on object type 
- limit ownership to "Власність" \ "Спільна власність"

**Comment by pro100olga** [comment]
Checked on 500K documents (annual declarations from 2017) using [this code](https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020)

**All ok. Closed.** 

**Final description of the flag:**
Check all estate objects. Raise the flag if there is an object for which:
- object is located not in Ukraine AND
- declarant or family member has right (Власність \ Спільна власність) for this object 
Any type of estate is considered here.
