### ISSUE TITLE
estate_purch_no_cost_flag: limit ownership

### ISSUE THREAD

**Issue by pro100olga** [excieve/dragnet#45]
For estate_purch_no_cost_flag consider only estate objects, where rights section has key of declarant ('1') or family (['step_2'].keys()) and at the same time ownershipType is one of the following: 'Власність', 'Спільна власність'

Smth like this:

```
for k in decl['data']['step_3'].keys():
    
    for right in decl['data']['step_3'][k]['rights'].keys():
        
        if right in list(r['declaration']['unified_source']['step_2'].keys()) + ['1']:
        
            if decl['data']['step_3'][k]['rights'][right]['ownershipType'] in ['Власність', 'Спільна власність']:
                
                # this object should be considered, including also requirement for owning date andcost missing
```

**Comment by dchaplinsky** [comment]
Should be fixed now.

**Comment by pro100olga** [comment]
Checked on 500K documents from annual 2017 decl.
~2K mismatches

1) False, but should be True:

nacp_de235a85-65ad-476f-a89f-e337c8b89445
nacp_edcde484-61f1-47d9-b69a-19c1c38b4898
nacp_edacd9e7-0fa5-4e3d-9fa0-ce8e91093463
nacp_ed9bb50e-b8d9-4db0-9048-eb30509c45a6

Is it possible that ownership is checked only for declarant, but not family members?
If so, please add check on family members as well

nacp_edc68aae-c4c2-4013-bb28-5cbf47e514a2 - interesting case here
For estate object in json "owningDate": "31.12.2017", but  "owningDate_extendedstatus": "3" (член сім'ї не надав інформацію)
html does not show date
I checked only date itself, so flag was assigned True

2) True, but should be False:
nacp_4b389515-04bc-4271-8660-af03cf464b4d 
nacp_ae44918a-367c-40e4-8af4-48dba87544e6
nacp_ab8affea-9696-46f2-b025-a9f671549e4a 

Do you also consider costAssessment (in addition to costDate)?
If no, please add it

**Comment by dchaplinsky** [comment]
First set of problems is already fixed.

Second one (True but should be False), I don't agree with this ones:
https://declarations.com.ua/declaration/nacp_4b389515-04bc-4271-8660-af03cf464b4d
https://declarations.com.ua/declaration/nacp_ae44918a-367c-40e4-8af4-48dba87544e6

In my opinion, they are perfectly valid

wrt:
Do you also consider costAssessment (in addition to costDate)?
Do you mean, that both should be hidden (AND clause, not OR)?

**Comment by pro100olga** [comment]
> Do you mean, that both should be hidden (AND clause, not OR)?

Yes, please

Checked mismatches from 1st set - all ok.

Second set. 
nacp_4b389515-04bc-4271-8660-af03cf464b4d - this one should be resolved by adding cost assessment check (AND)
nacp_ae44918a-367c-40e4-8af4-48dba87544e6 - why do you think it should be True? There is no object acquired in 2017 (but there is one where date is hidden - however I do not think we should count it)

**Comment by dchaplinsky** [comment]
Okay, I've fixed a function that was used to validate ownership. Previously
it checked all the rights on the vehicle/real estate, and if there was at
least one right of ownership/coownership it said it's okay. But in those
cases above there are ownership/coownership rights for third persons (while
they was declared by declarant or his/her family).
I've made amendments to that function, it might affect following flags:
has_foreign_real_estate
estate_purch_no_cost
estate_has_hidden_cost
has_vehicle
vehicle_purch_no_cost
has_luxury_cars_v2

**Comment by pro100olga** [comment]
Checked on 500K documents (annual declarations from 2017) using [this code](https://github.com/pro100olga/declarations/tree/master/bi/red_flags/flags_03_2020)

**All ok. Closed.** 

**Final description of the flag:**
Check all estate objects. Raise the flag if there is an object for which:
- date of owning is during the reported year AND
- declarant or family member has right (Власність \ Спільна власність) for this object AND
- cost of the object is not provided or zero (consider both cost at purchase moment and current assessment - both should be not provided or zero)
