### ISSUE TITLE
Temporary variables from CoucbDB views are leaking into DB

### ISSUE THREAD

**Issue by dchaplinsky** [excieve/dragnet#6]
Or so it seems.

I've compared results of old and new export on the same set of documents, here is the diff:
https://gist.github.com/dchaplinsky/1c84a0f47d8ea65b5808939ba15942a3

**Comment by dchaplinsky** [comment]
rev and other couchdb fields are expected, difference in data format of aggregated fields is expected too.

But pay an attention to records like that: https://gist.github.com/dchaplinsky/1c84a0f47d8ea65b5808939ba15942a3#file-decls_100000-diff-L115

**Comment by excieve** [comment]
These are not temporary and not leaking. In fact, they're not coming from views but actually from the import preprocessing. So that's expected.

**Comment by dchaplinsky** [comment]
Is there a way to at least prefix them?

**Comment by excieve** [comment]
That's certainly possible. Will work something out if it's causing problems.

**Comment by dchaplinsky** [comment]
Well. This data is later provided through API and data dumps and it's a bit unpleasant to supply such an altered data to end users without at least warning them. Prefix might help here.

**Comment by dchaplinsky** [comment]
Thanks
